NUMBER_OF_SLICES_DD=$(printf "%02d" ${NUMBER_OF_SLICES})
if [[ ${NUMBER_OF_SLICES} -eq 1 ]]
then
    FUNCTION_NAME="${PROJECT_NAME}_01_slice"
else
    FUNCTION_NAME="${PROJECT_NAME}_${NUMBER_OF_SLICES_DD}_slices"
fi
LAMBDA_CODE="../lambda_code"
INPUT_IMAGE_PATH="../models/${PROJECT_NAME}/${IMAGE_FILE}"
PACKAGES_PATH="../packages"
PACKAGE_PATH="${PACKAGES_PATH}/${PROJECT_NAME}"
ZIP_PACKAGE="${FUNCTION_NAME}.zip"
ZIP_PACKAGE_PATH="${PACKAGE_PATH}/${ZIP_PACKAGE}"
EVENTS_PATH="../events"
LAMBDA_HANDLER="src/lambda_handler"
LAMBDA_HANDLER_PY="${LAMBDA_HANDLER}.py"
LAMBDA_REQUIREMENTS="${LAMBDA_CODE}/projects/${PROJECT_NAME}/${PROJECT_NAME}_lambda_requirements.txt"
