#!/bin/bash

### FILE TO BE CONFIGURED MANUALLY ###

#MOBILEDET:
PROJECT_NAME="mobiledet"
S3_BUCKET="onnx-mobiledet-bucket"
IMAGE_FILE="img_resized.npy"
EXECUTION_TIMEOUT=30
FUNCTION_MEMORY=256

#EFFICIENTDET:
#PROJECT_NAME="efficientdet"
#S3_BUCKET="onnx-efficientdet-bucket"
#IMAGE_FILE="img_efficientdet.png"
#EXECUTION_TIMEOUT=30
#FUNCTION_MEMORY=1536

#NUMBER OF SLICES:
NUMBER_OF_SLICES=2
