#!/bin/bash

### TO BE CONFIGURED MANUALLY ###
#MOBILEDET:
PROJECT_NAME="mobiledet"
S3_BUCKET="onnx-mobiledet-bucket"
IMAGE_FILE="img_resized.npy"
EXECUTION_TIMEOUT=30
FUNCTION_MEMORY=256

#EFFICIENTDET:
#PROJECT_NAME="efficientdet"
#S3_BUCKET="onnx-efficientdet-bucket"
#IMAGE_FILE="img_efficientdet.png"
#EXECUTION_TIMEOUT=30
#FUNCTION_MEMORY=1536

# NUMBER OF SLICES:
NUMBER_OF_SLICES=2

#################################

FUNCTION_NAME="${PROJECT_NAME}_${NUMBER_OF_SLICES}_slices"
LAMBDA_CODE="../lambda_code"
INPUT_IMAGE_PATH="../models/${PROJECT_NAME}/${IMAGE_FILE}"
PACKAGES_PATH="../packages"
PACKAGE_PATH="${PACKAGES_PATH}/${PROJECT_NAME}"
ZIP_PACKAGE="${FUNCTION_NAME}.zip"
ZIP_PACKAGE_PATH="${PACKAGE_PATH}/${ZIP_PACKAGE}"
EVENTS_PATH="../events"
LAMBDA_HANDLER="projects/${PROJECT_NAME}/${PROJECT_NAME}_lambda"
LAMBDA_HANDLER_PY="${LAMBDA_HANDLER}.py"
LAMBDA_REQUIREMENTS="${LAMBDA_CODE}/projects/${PROJECT_NAME}/${PROJECT_NAME}_lambda_requirements.txt"


